# Created by: Douglas Thrift <douglas@douglasthrift.net>
# $FreeBSD: head/textproc/rubygem-yard-chef/Makefile 414136 2016-04-27 21:57:31Z swills $

PORTNAME=	yard-chef
PORTVERSION=	2.0.0
CATEGORIES=	textproc devel rubygems
MASTER_SITES=	RG

MAINTAINER=	douglas@douglasthrift.net
COMMENT=	YARD plugin for Chef

LICENSE=	MIT

RUN_DEPENDS=	rubygem-yard>=0.9.9:textproc/rubygem-yard \
		rubygem-redcarpet>=2.1.1:textproc/rubygem-redcarpet

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
