# Created by: Douglas Thrift <douglas@douglasthrift.net>
# $FreeBSD: head/dns/rubygem-simpleidn/Makefile 459072 2018-01-15 15:34:16Z swills $

PORTNAME=	simpleidn
PORTVERSION=	0.1.1
CATEGORIES=	dns rubygems
MASTER_SITES=	RG

MAINTAINER=	douglas@douglasthrift.net
COMMENT=	Easy conversion from IDNA strings to unicode strings and vice-versa

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENCE

RUN_DEPENDS=	rubygem-unf>=0.1.4:textproc/rubygem-unf

NO_ARCH=	yes
USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
